spring:
  output.ansi.enabled: always
  profiles:
    active: local
  thymeleaf:
    enabled: true
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sbb_test?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: lldj
    password: lldj1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    com.ll.dj: debug
    org.hibernate.type.descriptor.sql: trace